import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/navigation";

const Exo2 = Exo_2({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={Exo2.className}>
                <Header />
                <main className="overflow-x-hidden container space-y-20 lg:py-4 2xl:py-10">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
